In [ ]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_12_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df = pd.concat(map(pd.read_csv, files), ignore_index=True)
df.to_csv('out.csv',index=False)
print("df.head()");
df.head()

In [ ]:
df

In [ ]:
df.to_csv('out.csv',index=False)
print("df.head()");
df.head()

In [ ]:
df

In [ ]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_12_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df2 = pd.concat(map(pd.read_csv, files), ignore_index=True)
print("Did Concat")
df2.to_csv('out2.csv',index=False)
print("df2.head()");
df2

In [ ]:
    for row in df2:
            print(row)

In [ ]:
df2[18816537:18817537]

In [1]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_4_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df3 = pd.concat(map(pd.read_csv, files), ignore_index=True)
print("Did Concat")
df3.to_csv('out3.csv',index=False)
print("Printing df3.head()");
df3

Resultant CSV after joining all CSV files at a particular location...

C:\Users\BZ Northwestern BC\anaconda3\lib\site-packages\pandas\core\reshape\concat.py:294: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  op = _Concatenator(

Did Concat
df3.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499184,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
6499185,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
6499186,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
6499187,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
6499188,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

In [2]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_4_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df3 = pd.concat(map(pd.read_csv, files), ignore_index=True)
print("Did Concat")
df3.to_csv('out3.csv',index=False)
print("Printing df3.head()");
df3

Resultant CSV after joining all CSV files at a particular location...

C:\Users\BZ Northwestern BC\anaconda3\lib\site-packages\pandas\core\reshape\concat.py:294: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  op = _Concatenator(

Did Concat
Printing df3.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6499184,5EBE9D296B9D3E3C,classic_bike,2022-04-22 13:08:15,2022-04-22 13:29:31,Allen St & Rivington St,5414.06,W 29 St & 9 Ave,6416.06,40.720196,-73.989978,40.750073,-73.998393,member
6499185,B66382DEDA84C464,classic_bike,2022-04-13 17:10:49,2022-04-13 17:26:08,St. Nicholas Terrace & Convent Ave,7937.15,E 138 St & Grand Concourse,7803.08,40.821294,-73.947868,40.813224,-73.930605,member
6499186,9EC4C49BE4CB1A09,classic_bike,2022-04-12 15:58:47,2022-04-12 16:41:17,E 88 St & 1 Ave,7235.13,E 91 St & 2 Ave,7286.01,40.778301,-73.948813,40.781153,-73.949630,member
6499187,C0188AB9FAEAA143,electric_bike,2022-04-28 15:52:49,2022-04-28 16:06:31,W 55 St & 6 Ave,6809.09,E 91 St & 2 Ave,7286.01,40.763189,-73.978434,40.781153,-73.949630,member
6499188,E8C2F305866DF134,electric_bike,2022-04-11 19:55:31,2022-04-11 20:09:19,W 87 St & West End Ave,7484.05,E 91 St & 2 Ave,7286.01,40.789622,-73.977570,40.781153,-73.949630,member

In [4]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_3_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df4 = pd.concat(map(pd.read_csv, files), ignore_index=True)
print("Did Concat")
df4.to_csv('out4.csv',index=False)
print("Printing df4.head()");
df4

Resultant CSV after joining all CSV files at a particular location...

C:\Users\BZ Northwestern BC\anaconda3\lib\site-packages\pandas\core\reshape\concat.py:294: DtypeWarning: Columns (5,7) have mixed types.Specify dtype option on import or set low_memory=False.
  op = _Concatenator(

Did Concat
Printing df4.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,55262E4365A955A2,classic_bike,2022-01-18 08:23:52,2022-01-18 08:28:18,Boerum Pl\t& Pacific St,4488.09,Clinton St & Joralemon St,4605.04,40.688489,-73.991160,40.692395,-73.993379,member
1,D272F1B15D841EC0,classic_bike,2022-01-21 09:03:22,2022-01-21 09:05:44,E 12 St & Ave C,5616.08,E 10 St & Avenue A,5659.05,40.727243,-73.976831,40.727408,-73.981420,member
2,D1FCEF55EB4A807F,classic_bike,2022-01-22 14:28:32,2022-01-22 14:53:18,W 21 St & 6 Ave,6140.05,W 44 St & 11 Ave,6756.05,40.741740,-73.994156,40.762009,-73.996975,member
3,E9CBDC6A0162C068,electric_bike,2022-01-19 14:49:47,2022-01-19 14:54:02,38 St & 30 Ave,6850.01,Crescent St & 30 Ave,6958.06,40.764175,-73.915840,40.768692,-73.924957,member
4,2177A5B57326CE9B,electric_bike,2022-01-16 14:36:06,2022-01-16 14:44:06,Pacific St & Nevins St,4362.04,Clinton St & Tillary St,4748.07,40.685376,-73.983021,40.696233,-73.991421,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4179571,79E49EA8727CA662,classic_bike,2022-03-30 21:12:45,2022-03-30 21:22:15,E 72 St & York Ave,6889.12,E 58 St & 3 Ave,6762.02,40.766638,-73.953483,40.760958,-73.967245,member
4179572,9C4F6A095779AAE2,electric_bike,2022-03-21 09:33:21,2022-03-21 09:39:45,W 48 St & Rockefeller Plaza,6626.11,E 58 St & 3 Ave,6762.02,40.757769,-73.979294,40.760958,-73.967245,member
4179573,C1966A89B5078124,electric_bike,2022-03-04 14:31:36,2022-03-04 14:43:16,Central Park West & W 85 St,7354.01,E 58 St & 3 Ave,6762.02,40.784760,-73.969862,40.760958,-73.967245,member
4179574,A11D1F167EF1B8C6,classic_bike,2022-03-18 18:43:43,2022-03-18 18:53:41,W 56 St & 6 Ave,6809.07,E 58 St & 3 Ave,6762.02,40.763406,-73.977225,40.760958,-73.967245,member
4179575,74A6A40E386BE88F,electric_bike,2022-03-10 17:21:52,2022-03-10 17:29:53,5 Ave & E 72 St,7100.07,E 58 St & 3 Ave,6762.02,40.772828,-73.966853,40.760958,-73.967245,casual

In [ ]:
import pandas as pd
import glob
import os

# setting the path for joining multiple files
# files = os.path.join("C:\\Users\\amit_\\Desktop\\", "sales*.csv")
# files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\", "20211*.csv") 
files = os.path.join("C:\\Users\\BZ Northwestern BC\\Class\\Tableau-Challenge\\Key_3_Month_citibike-tripdata\\", "*citibike-tripdata*.csv") 


# list of merged files returned
files = glob.glob(files)

print("Resultant CSV after joining all CSV files at a particular location...");

# joining files with concat and read_csv
df4 = pd.concat(map(pd.read_csv, files), ignore_index=True)
print("Did Concat")
df4.to_csv('out4.csv',index=False)
print("Printing df4.head()");
df4